name: Generate Isometric 3D Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          mv profile-3d-contrib dist/

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge jsDelivr cache
        run: |
          curl -s "https://purge.jsdelivr.net/gh/nagarajhegde174-beep/nagarajhegde174-beep@output/profile-3d-contrib/profile-night-rainbow.svg"
